"""enterprise_foundations

Revision ID: 0001
Revises:
Create Date: 2026-08-15 15:57:28.017368
"""
from collections.abc import Sequence

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('code_version', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=200), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('cost_amount', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_runs_parent_run_id_analysis_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_dataset_hash'), 'analysis_runs', ['dataset_hash'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=200), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slice_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_table('opportunities',
    sa.Column('opportunity_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('component', sa.String(length=120), nullable=True),
    sa.Column('impact_scope', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('safety_level', sa.String(length=32), nullable=True),
    sa.Column('differentiation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_product'), 'opportunities', ['product'], unique=False)
    op.create_index(op.f('ix_opportunities_safety_level'), 'opportunities', ['safety_level'], unique=False)
    op.create_table('review_decisions',
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_table('sources',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('connection_status', sa.String(length=32), nullable=False),
    sa.Column('authorization_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    op.create_table('taxonomy_versions',
    sa.Column('product_scope', sa.String(length=200), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_by', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['taxonomy_versions.id'], name=op.f('fk_taxonomy_versions_parent_version_id_taxonomy_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxonomy_versions'))
    )
    op.create_index(op.f('ix_taxonomy_versions_product_scope'), 'taxonomy_versions', ['product_scope'], unique=False)
    op.create_table('action_items',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('collaborating_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_system_ref', sa.String(length=1024), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_action_items_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    op.create_table('clusters',
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=200), nullable=False),
    sa.Column('current_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_signal_type', sa.String(length=50), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('representative_record_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], name=op.f('fk_clusters_taxonomy_version_id_taxonomy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters'))
    )
    op.create_table('competitor_evidence',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('competitor', sa.String(length=200), nullable=False),
    sa.Column('source_ref', sa.String(length=1024), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('comparison_dimension', sa.String(length=200), nullable=False),
    sa.Column('evidence_strength', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_competitor_evidence_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_evidence'))
    )
    op.create_table('ingestion_batches',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('deduplicated_count', sa.Integer(), nullable=False),
    sa.Column('quarantined_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_batches_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_batches'))
    )
    op.create_index(op.f('ix_ingestion_batches_source_id'), 'ingestion_batches', ['source_id'], unique=False)
    op.create_table('model_releases',
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=200), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], name=op.f('fk_model_releases_evaluation_run_id_evaluation_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['model_releases.id'], name=op.f('fk_model_releases_rollback_of_id_model_releases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_releases'))
    )
    op.create_table('taxonomy_revisions',
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], name=op.f('fk_taxonomy_revisions_taxonomy_version_id_taxonomy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxonomy_revisions'))
    )
    op.create_table('outcome_measurements',
    sa.Column('action_item_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], name=op.f('fk_outcome_measurements_action_item_id_action_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome_measurements'))
    )
    op.create_table('voice_records',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_object_ref', sa.String(length=1024), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('privacy_status', sa.String(length=32), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], name=op.f('fk_voice_records_ingestion_batch_id_ingestion_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_voice_records_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_records')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_voice_source_external')
    )
    op.create_index(op.f('ix_voice_records_content_hash'), 'voice_records', ['content_hash'], unique=False)
    op.create_index(op.f('ix_voice_records_ingestion_batch_id'), 'voice_records', ['ingestion_batch_id'], unique=False)
    op.create_index(op.f('ix_voice_records_product'), 'voice_records', ['product'], unique=False)
    op.create_index(op.f('ix_voice_records_sku'), 'voice_records', ['sku'], unique=False)
    op.create_index(op.f('ix_voice_records_source_id'), 'voice_records', ['source_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('voice_record_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker_role', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_record_id'], ['voice_records.id'], name=op.f('fk_conversation_turns_voice_record_id_voice_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('voice_record_id', 'turn_index', name='uq_voice_turn_index')
    )
    op.create_table('golden_examples',
    sa.Column('voice_record_id', sa.UUID(), nullable=False),
    sa.Column('redacted_input', sa.Text(), nullable=False),
    sa.Column('expected_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dispute_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_record_id'], ['voice_records.id'], name=op.f('fk_golden_examples_voice_record_id_voice_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_examples'))
    )
    op.create_table('privacy_findings',
    sa.Column('voice_record_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('recognizer', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_record_id'], ['voice_records.id'], name=op.f('fk_privacy_findings_voice_record_id_voice_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_findings'))
    )
    op.create_table('signals',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('voice_record_id', sa.UUID(), nullable=False),
    sa.Column('signal_index', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('object_name', sa.String(length=200), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('calibration_status', sa.String(length=32), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_signals_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_record_id'], ['voice_records.id'], name=op.f('fk_signals_voice_record_id_voice_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('analysis_run_id', 'voice_record_id', 'signal_index', name='uq_run_voice_signal')
    )
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('cluster_memberships',
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('assignment_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_cluster_memberships_cluster_id_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_cluster_memberships_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], name=op.f('fk_cluster_memberships_taxonomy_version_id_taxonomy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_memberships')),
    sa.UniqueConstraint('taxonomy_version_id', 'signal_id', name='uq_taxonomy_signal_membership')
    )
    op.create_table('embeddings',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_embeddings_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('signal_id', 'model_version', name='uq_embedding_signal_model')
    )
    op.create_table('opportunity_evidence',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('voice_record_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('evidence_direction', sa.String(length=16), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_direction IN ('support', 'oppose')", name=op.f('ck_opportunity_evidence_evidence_direction')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_evidence_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_opportunity_evidence_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_record_id'], ['voice_records.id'], name=op.f('fk_opportunity_evidence_voice_record_id_voice_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_evidence')),
    sa.UniqueConstraint('opportunity_id', 'voice_record_id', 'evidence_direction', name='uq_opportunity_voice_direction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_evidence')
    op.drop_table('embeddings')
    op.drop_table('cluster_memberships')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('privacy_findings')
    op.drop_table('golden_examples')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_voice_records_source_id'), table_name='voice_records')
    op.drop_index(op.f('ix_voice_records_sku'), table_name='voice_records')
    op.drop_index(op.f('ix_voice_records_product'), table_name='voice_records')
    op.drop_index(op.f('ix_voice_records_ingestion_batch_id'), table_name='voice_records')
    op.drop_index(op.f('ix_voice_records_content_hash'), table_name='voice_records')
    op.drop_table('voice_records')
    op.drop_table('outcome_measurements')
    op.drop_table('taxonomy_revisions')
    op.drop_table('model_releases')
    op.drop_index(op.f('ix_ingestion_batches_source_id'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_table('competitor_evidence')
    op.drop_table('clusters')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_taxonomy_versions_product_scope'), table_name='taxonomy_versions')
    op.drop_table('taxonomy_versions')
    op.drop_table('sources')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_opportunities_safety_level'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_product'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_analysis_runs_dataset_hash'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
