"""opportunity_priority_override

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-15 16:13:56.166453
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('priority_override', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_opportunities_priority_override'), 'opportunities', ['priority_override'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_priority_override'), table_name='opportunities')
    op.drop_column('opportunities', 'priority_override')
    # ### end Alembic commands ###
