"""golden sample order

Revision ID: ea7c970068f5
Revises: f8899c093853
Create Date: 2026-08-15 16:20:01.430829
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ea7c970068f5'
down_revision: str | Sequence[str] | None = 'f8899c093853'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('golden_examples', sa.Column('sample_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('golden_examples', 'sample_order')
    # ### end Alembic commands ###
