"""golden review release gates

Revision ID: f8899c093853
Revises: 0002
Create Date: 2026-08-15 16:19:36.170678
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f8899c093853'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_reviews',
    sa.Column('golden_example_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=200), nullable=False),
    sa.Column('review_role', sa.String(length=32), nullable=False),
    sa.Column('label_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['golden_example_id'], ['golden_examples.id'], name=op.f('fk_golden_reviews_golden_example_id_golden_examples'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_reviews')),
    sa.UniqueConstraint('golden_example_id', 'reviewer_id', name='uq_golden_example_reviewer')
    )
    op.add_column('golden_examples', sa.Column('analysis_run_id', sa.UUID(), nullable=False))
    op.add_column('golden_examples', sa.Column('primary_signal', sa.String(length=50), nullable=False))
    op.add_column('golden_examples', sa.Column('cluster_id', sa.UUID(), nullable=False))
    op.add_column('golden_examples', sa.Column('sampling_seed', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_golden_sample_run_seed_voice', 'golden_examples', ['analysis_run_id', 'sampling_seed', 'voice_record_id'])
    op.create_foreign_key(op.f('fk_golden_examples_analysis_run_id_analysis_runs'), 'golden_examples', 'analysis_runs', ['analysis_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_golden_examples_cluster_id_clusters'), 'golden_examples', 'clusters', ['cluster_id'], ['id'], ondelete='RESTRICT')
    op.add_column('model_releases', sa.Column('reason_code', sa.String(length=100), nullable=True))
    op.add_column('model_releases', sa.Column('gate_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_releases', 'gate_results')
    op.drop_column('model_releases', 'reason_code')
    op.drop_constraint(op.f('fk_golden_examples_cluster_id_clusters'), 'golden_examples', type_='foreignkey')
    op.drop_constraint(op.f('fk_golden_examples_analysis_run_id_analysis_runs'), 'golden_examples', type_='foreignkey')
    op.drop_constraint('uq_golden_sample_run_seed_voice', 'golden_examples', type_='unique')
    op.drop_column('golden_examples', 'sampling_seed')
    op.drop_column('golden_examples', 'cluster_id')
    op.drop_column('golden_examples', 'primary_signal')
    op.drop_column('golden_examples', 'analysis_run_id')
    op.drop_table('golden_reviews')
    # ### end Alembic commands ###
